args:
  image2video: True # True for image2video, False for text2video
  latent_channels: 16
  mode: inference
  # load: "/pfs/mt-1oY5F7/chenshuo/CogVideo/CogVideoX-5B-I2V-sat/transformer/" # This is for Full model without lora adapter
  load: "/home/chenshuo/DimensionX_code/checkpoints/" # This is for Full model without lora adapter
  batch_size: 1
  input_type: txt
  input_file: configs/test_i2v.txt
  sampling_image_size: [320, 480]
  sampling_num_frames: 37  # Must be 13, 11 or 9 , 37 for 145
  sampling_fps: 8
#  fp16: True # For CogVideoX-2B
  bf16: True # For CogVideoX-5B and CoGVideoX-5B-I2V
  output_dir: outputs/
  force_inference: True